### PR TITLE
Extracted DatabaseReader.Metadata property to interface

### PR DESCRIPTION
**Pull request by mihai-netvision**
Extracted DatabaseReader.Metadata property to the IGeoIP2DatabaseReader inferface

### CODE REVIEW

**Comment by mihai-netvision** [comment]
#134

**Comment by oschwald** [comment]
This seems ok, but it is a breaking change. Perhaps we can merge it next time we are doing a major release.

**Comment by mihai-netvision** [comment]
Indeed, it is a breaking change. Is there a roadmap or a rough estimation of the time frame for the next major release?

**Comment by mihai-netvision** [comment]
There is also the option to have a new interface... `IMetadataProvider `or something similar added to the `DatabaseReader `type, for exposing the `Metadata `property. I believe that would not consist in a breaking change, however I'm not sure you'd fancy that idea.

**Comment by oschwald** [comment]
I am merging this now as we are doing a major release soon. Thanks!.

**Pull request merged**
